"""Add import_jobs table

Revision ID: 3731febd74cf
Revises: c054123ae212
Create Date: 2025-12-09 01:44:16.835763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3731febd74cf"
down_revision: Union[str, None] = "c054123ae212"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("weeks", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("grade_games", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="importjobstatus"
            ),
            nullable=False,
        ),
        sa.Column("current_step", sa.String(length=200), nullable=True),
        sa.Column("games_processed", sa.Integer(), nullable=False),
        sa.Column("total_games", sa.Integer(), nullable=False),
        sa.Column("teams_created", sa.Integer(), nullable=False),
        sa.Column("players_created", sa.Integer(), nullable=False),
        sa.Column("games_created", sa.Integer(), nullable=False),
        sa.Column("games_updated", sa.Integer(), nullable=False),
        sa.Column("games_graded", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_jobs_admin_user_id"),
        "import_jobs",
        ["admin_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_jobs_season"), "import_jobs", ["season"], unique=False
    )
    op.create_index(
        op.f("ix_import_jobs_started_at"), "import_jobs", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_import_jobs_status"), "import_jobs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_import_jobs_status"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_started_at"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_season"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_admin_user_id"), table_name="import_jobs")
    op.drop_table("import_jobs")
    # ### end Alembic commands ###
