"""update_pick_submission_models

Revision ID: db6a740a728e
Revises: f11c7013f8de
Create Date: 2025-12-05 16:25:09.652042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db6a740a728e'
down_revision: Union[str, None] = 'f11c7013f8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_game_pick', 'picks', ['user_id', 'game_id'])
    op.drop_column('picks', 'pick_type')
    op.drop_column('picks', 'snapshot_odds')
    op.add_column('players', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('players', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_players_last_name', table_name='players')
    op.drop_index('ix_players_external_id', table_name='players')
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    op.drop_column('players', 'league')
    op.add_column('teams', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('name', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('abbreviation', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('city', sa.String(), nullable=False))
    op.drop_index('ix_teams_team_abbreviation', table_name='teams')
    op.drop_index('ix_teams_team_name', table_name='teams')
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.drop_column('teams', 'league')
    op.drop_column('teams', 'team_name')
    op.drop_column('teams', 'team_abbreviation')
    op.drop_column('teams', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('league', postgresql.ENUM('NFL', 'NBA', 'NHL', 'MLB', 'NCAAF', name='league'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.create_index('ix_teams_team_name', 'teams', ['team_name'], unique=False)
    op.create_index('ix_teams_team_abbreviation', 'teams', ['team_abbreviation'], unique=False)
    op.drop_column('teams', 'city')
    op.drop_column('teams', 'abbreviation')
    op.drop_column('teams', 'name')
    op.drop_column('teams', 'external_id')
    op.add_column('players', sa.Column('league', postgresql.ENUM('NFL', 'NBA', 'NHL', 'MLB', 'NCAAF', name='league'), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.create_index('ix_players_external_id', 'players', ['external_id'], unique=False)
    op.create_index('ix_players_last_name', 'players', ['last_name'], unique=False)
    op.alter_column('players', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('players', 'name')
    op.add_column('picks', sa.Column('snapshot_odds', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('picks', sa.Column('pick_type', postgresql.ENUM('FTD', 'ATTD', name='picktype'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_game_pick', 'picks', type_='unique')
    # ### end Alembic commands ###

