"""Add scoring system fields to Pick, User, and Game models

Revision ID: dd889087ef87
Revises: acce9ffc1c73
Create Date: 2025-12-07 23:30:07.421879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd889087ef87"
down_revision: Union[str, None] = "acce9ffc1c73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "all_td_scorer_player_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "games", sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "games",
        sa.Column(
            "is_manually_scored", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "picks", sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "picks",
        sa.Column("ftd_points", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "picks",
        sa.Column("attd_points", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "picks",
        sa.Column("total_points", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("picks", sa.Column("override_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "picks", sa.Column("override_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(None, "picks", "users", ["override_by_user_id"], ["id"])
    op.add_column(
        "users",
        sa.Column("total_score", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "users",
        sa.Column("total_wins", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "users",
        sa.Column("total_losses", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "total_losses")
    op.drop_column("users", "total_wins")
    op.drop_column("users", "total_score")
    op.drop_constraint(None, "picks", type_="foreignkey")
    op.drop_column("picks", "override_at")
    op.drop_column("picks", "override_by_user_id")
    op.drop_column("picks", "total_points")
    op.drop_column("picks", "attd_points")
    op.drop_column("picks", "ftd_points")
    op.drop_column("picks", "scored_at")
    op.drop_column("games", "is_manually_scored")
    op.drop_column("games", "scored_at")
    op.drop_column("games", "all_td_scorer_player_ids")
    # ### end Alembic commands ###
